# GitHub Actions désactivé - Utilisation de Vercel pour le déploiement
# Vercel est configuré et fonctionne parfaitement
# 
# Pour déployer manuellement :
# 1. cd web
# 2. npx vercel --prod --yes
#
# URL de production : https://web-cibtk39mt-shalomdevs-projects.vercel.app

name: Deploy to GitHub Pages (DISABLED)

on:
  workflow_dispatch:  # Seulement manuel pour éviter les erreurs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: false  # Désactivé
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build
      run: npm run build
      env:
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL || 'https://web-production-39a0b.up.railway.app/api/v1' }}
        
    - name: Info
      run: echo "GitHub Actions désactivé - Utilisez Vercel pour le déploiement"
